// <auto-generated />
namespace DacSan3Mien.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addcolumnname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolumnname));
        
        string IMigrationMetadata.Id
        {
            get { return "201812201656005_add-column-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
